<?php

namespace ContainerN0nZYcU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrderStateMachineService extends Eccube_KernelDevDebugContainer
{
    /**
     * Gets the private 'Eccube\Service\OrderStateMachine' shared autowired service.
     *
     * @return \Eccube\Service\OrderStateMachine
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Eccube'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'OrderStateMachine.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Eccube'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'PurchaseFlow'.\DIRECTORY_SEPARATOR.'DiscountProcessor.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Eccube'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'PurchaseFlow'.\DIRECTORY_SEPARATOR.'PurchaseProcessor.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Eccube'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'PurchaseFlow'.\DIRECTORY_SEPARATOR.'Processor'.\DIRECTORY_SEPARATOR.'PointProcessor.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Eccube'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'PurchaseFlow'.\DIRECTORY_SEPARATOR.'Processor'.\DIRECTORY_SEPARATOR.'AbstractPurchaseProcessor.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Eccube'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'PurchaseFlow'.\DIRECTORY_SEPARATOR.'Processor'.\DIRECTORY_SEPARATOR.'StockReduceProcessor.php';

        $a = ($container->privates['debug.state_machine.order'] ?? self::getDebug_StateMachine_OrderService($container));

        if (isset($container->privates['Eccube\\Service\\OrderStateMachine'])) {
            return $container->privates['Eccube\\Service\\OrderStateMachine'];
        }
        $b = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['Eccube\\Service\\OrderStateMachine'])) {
            return $container->privates['Eccube\\Service\\OrderStateMachine'];
        }
        $c = ($container->privates['Eccube\\Service\\PointHelper'] ?? $container->load('getPointHelperService'));

        if (isset($container->privates['Eccube\\Service\\OrderStateMachine'])) {
            return $container->privates['Eccube\\Service\\OrderStateMachine'];
        }

        return $container->privates['Eccube\\Service\\OrderStateMachine'] = new \Eccube\Service\OrderStateMachine($a, ($container->privates['Eccube\\Repository\\Master\\OrderStatusRepository'] ?? $container->load('getOrderStatusRepositoryService')), new \Eccube\Service\PurchaseFlow\Processor\PointProcessor($b, $c), new \Eccube\Service\PurchaseFlow\Processor\StockReduceProcessor(($container->privates['Eccube\\Repository\\ProductStockRepository'] ?? $container->load('getProductStockRepositoryService')), $b));
    }
}
