<?php

namespace ContainerUaYVmUP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RgQuQsxService extends Eccube_KernelInstallContainer
{
    /*
     * Gets the private '.service_locator.rgQuQsx' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rgQuQsx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'systemService' => ['services', 'Eccube\\Service\\SystemService', 'getSystemServiceService', true],
        ], [
            'systemService' => 'Eccube\\Service\\SystemService',
        ]);
    }
}
