<?php

namespace ContainerUaYVmUP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEccube_LoggerService extends Eccube_KernelInstallContainer
{
    /*
     * Gets the public 'eccube.logger' shared autowired service.
     *
     * @return \Eccube\Log\Logger
     */
    public static function do($container, $lazyLoad = true)
    {
        if (true === $lazyLoad) {
            return $container->services['eccube.logger'] = $container->createProxy('LoggerGhostDc24f23', static fn () => \LoggerGhostDc24f23::createLazyGhost(static fn ($proxy) => self::do($container, $proxy)));
        }

        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'psr'.\DIRECTORY_SEPARATOR.'log'.\DIRECTORY_SEPARATOR.'Psr'.\DIRECTORY_SEPARATOR.'Log'.\DIRECTORY_SEPARATOR.'AbstractLogger.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Eccube'.\DIRECTORY_SEPARATOR.'Log'.\DIRECTORY_SEPARATOR.'Logger.php';

        return ($lazyLoad->__construct(($container->privates['Eccube\\Request\\Context'] ?? $container->load('getContextService')), ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)), ($container->services['monolog.logger.front'] ?? $container->load('getMonolog_Logger_FrontService')), ($container->services['monolog.logger.admin'] ?? $container->load('getMonolog_Logger_AdminService'))) && false ?: $lazyLoad);
    }
}
