<?php

namespace ContainerUaYVmUP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMobileDetectService extends Eccube_KernelInstallContainer
{
    /*
     * Gets the public 'Detection\MobileDetect' shared autowired service.
     *
     * @return \Detection\MobileDetect
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'mobiledetect'.\DIRECTORY_SEPARATOR.'mobiledetectlib'.\DIRECTORY_SEPARATOR.'Mobile_Detect.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'mobiledetect'.\DIRECTORY_SEPARATOR.'mobiledetectlib'.\DIRECTORY_SEPARATOR.'namespaced'.\DIRECTORY_SEPARATOR.'Detection'.\DIRECTORY_SEPARATOR.'MobileDetect.php';

        return $container->services['Detection\\MobileDetect'] = new \Detection\MobileDetect();
    }
}
