<?php

namespace ContainerUaYVmUP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPaymentStatusRepositoryService extends Eccube_KernelInstallContainer
{
    /*
     * Gets the private 'Plugin\AmazonPayV2_42_Bundle\Repository\PaymentStatusRepository' shared autowired service.
     *
     * @return \Plugin\AmazonPayV2_42_Bundle\Repository\PaymentStatusRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'app'.\DIRECTORY_SEPARATOR.'Plugin'.\DIRECTORY_SEPARATOR.'AmazonPayV2_42_Bundle'.\DIRECTORY_SEPARATOR.'Repository'.\DIRECTORY_SEPARATOR.'PaymentStatusRepository.php';

        return $container->privates['Plugin\\AmazonPayV2_42_Bundle\\Repository\\PaymentStatusRepository'] = new \Plugin\AmazonPayV2_42_Bundle\Repository\PaymentStatusRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
