<?php

namespace ContainerUaYVmUP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_Firewall_EventDispatcherLocatorService extends Eccube_KernelInstallContainer
{
    /*
     * Gets the private 'security.firewall.event_dispatcher_locator' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['security.firewall.event_dispatcher_locator'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['api' => #[\Closure(name: 'security.event_dispatcher.api', class: 'Symfony\\Component\\EventDispatcher\\EventDispatcher')] fn () => ($container->privates['security.event_dispatcher.api'] ?? $container->load('getSecurity_EventDispatcher_ApiService')), 'admin' => #[\Closure(name: 'security.event_dispatcher.admin', class: 'Symfony\\Component\\EventDispatcher\\EventDispatcher')] fn () => ($container->privates['security.event_dispatcher.admin'] ?? self::getSecurity_EventDispatcher_AdminService($container)), 'customer' => #[\Closure(name: 'security.event_dispatcher.customer', class: 'Symfony\\Component\\EventDispatcher\\EventDispatcher')] fn () => ($container->privates['security.event_dispatcher.customer'] ?? self::getSecurity_EventDispatcher_CustomerService($container))]);
    }
}
