<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBbFG9cz\Eccube_KernelProdDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBbFG9cz/Eccube_KernelProdDebugContainer.php') {
    touch(__DIR__.'/ContainerBbFG9cz.legacy');

    return;
}

if (!\class_exists(Eccube_KernelProdDebugContainer::class, false)) {
    \class_alias(\ContainerBbFG9cz\Eccube_KernelProdDebugContainer::class, Eccube_KernelProdDebugContainer::class, false);
}

return new \ContainerBbFG9cz\Eccube_KernelProdDebugContainer([
    'container.build_hash' => 'BbFG9cz',
    'container.build_id' => '79865112',
    'container.build_time' => 1762850159,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBbFG9cz');
