<?php

namespace ContainerFoEts6e;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_League_Oauth2Server_Command_DeleteClient_LazyService extends Eccube_KernelDevDebugContainer
{
    /**
     * Gets the private '.league.oauth2_server.command.delete_client.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'LazyCommand.php';

        return $container->privates['.league.oauth2_server.command.delete_client.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('league:oauth2-server:delete-client', [], 'Deletes an OAuth2 client', false, #[\Closure(name: 'league.oauth2_server.command.delete_client', class: 'League\\Bundle\\OAuth2ServerBundle\\Command\\DeleteClientCommand')] fn (): \League\Bundle\OAuth2ServerBundle\Command\DeleteClientCommand => ($container->privates['league.oauth2_server.command.delete_client'] ?? $container->load('getLeague_Oauth2Server_Command_DeleteClientService')));
    }
}
