<?php

namespace ContainerFoEts6e;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminCustomerSubscriberService extends Eccube_KernelDevDebugContainer
{
    /**
     * Gets the public 'Plugin\B2BConnector\Event\AdminCustomerSubscriber' shared autowired service.
     *
     * @return \Plugin\B2BConnector\Event\AdminCustomerSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'app'.\DIRECTORY_SEPARATOR.'Plugin'.\DIRECTORY_SEPARATOR.'B2BConnector'.\DIRECTORY_SEPARATOR.'Event'.\DIRECTORY_SEPARATOR.'AdminCustomerSubscriber.php';

        $a = ($container->privates['form.factory'] ?? $container->load('getForm_FactoryService'));

        if (isset($container->services['Plugin\\B2BConnector\\Event\\AdminCustomerSubscriber'])) {
            return $container->services['Plugin\\B2BConnector\\Event\\AdminCustomerSubscriber'];
        }
        $b = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->services['Plugin\\B2BConnector\\Event\\AdminCustomerSubscriber'])) {
            return $container->services['Plugin\\B2BConnector\\Event\\AdminCustomerSubscriber'];
        }

        return $container->services['Plugin\\B2BConnector\\Event\\AdminCustomerSubscriber'] = new \Plugin\B2BConnector\Event\AdminCustomerSubscriber($a, $b, ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)));
    }
}
