<?php

namespace ContainerFoEts6e;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEccube_Security_Logout_SuccessHandlerService extends Eccube_KernelDevDebugContainer
{
    /**
     * Gets the private 'eccube.security.logout.success_handler' shared autowired service.
     *
     * @return \Eccube\Security\Http\Authentication\EccubeLogoutSuccessHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Eccube'.\DIRECTORY_SEPARATOR.'Security'.\DIRECTORY_SEPARATOR.'Http'.\DIRECTORY_SEPARATOR.'Authentication'.\DIRECTORY_SEPARATOR.'EccubeLogoutSuccessHandler.php';

        return $container->privates['eccube.security.logout.success_handler'] = new \Eccube\Security\Http\Authentication\EccubeLogoutSuccessHandler(($container->privates['Eccube\\Request\\Context'] ?? self::getContextService($container)));
    }
}
