<?php

namespace ContainerFoEts6e;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMonolog_Handler_AmazonPayService extends Eccube_KernelDevDebugContainer
{
    /**
     * Gets the private 'monolog.handler.amazon_pay' shared service.
     *
     * @return \Monolog\Handler\FingersCrossedHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'monolog'.\DIRECTORY_SEPARATOR.'monolog'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Monolog'.\DIRECTORY_SEPARATOR.'Handler'.\DIRECTORY_SEPARATOR.'FingersCrossedHandler.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'monolog'.\DIRECTORY_SEPARATOR.'monolog'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Monolog'.\DIRECTORY_SEPARATOR.'Handler'.\DIRECTORY_SEPARATOR.'FingersCrossed'.\DIRECTORY_SEPARATOR.'ActivationStrategyInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'monolog'.\DIRECTORY_SEPARATOR.'monolog'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Monolog'.\DIRECTORY_SEPARATOR.'Handler'.\DIRECTORY_SEPARATOR.'FingersCrossed'.\DIRECTORY_SEPARATOR.'ErrorLevelActivationStrategy.php';

        $a = new \Monolog\Handler\RotatingFileHandler((\dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'log/dev/amazon_pay_v2.log'), 60, 'debug', true, NULL, false);
        $a->pushProcessor(($container->privates['monolog.processor.psr_log_message'] ??= new \Monolog\Processor\PsrLogMessageProcessor()));
        $a->setFilenameFormat('{filename}-{date}', 'Y-m-d');
        $a->setFormatter(new \Monolog\Formatter\LineFormatter('[%datetime%] %channel%.%level_name% [%extra.session_id%] [%extra.uid%] [%extra.user_id%] [%extra.class%:%extra.function%:%extra.line%] - %message% %context% [%extra.http_method%, %extra.url%, %extra.ip%, %extra.referrer%, %extra.user_agent%]'."\n".'', 'Y-m-d H:i:s.u'));

        return $container->privates['monolog.handler.amazon_pay'] = new \Monolog\Handler\FingersCrossedHandler($a, new \Monolog\Handler\FingersCrossed\ErrorLevelActivationStrategy('error'), 0, true, true, 'info');
    }
}
