<?php

namespace ContainerFoEts6e;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPluginGenerateCommandService extends Eccube_KernelDevDebugContainer
{
    /**
     * Gets the private 'Eccube\Command\PluginGenerateCommand' shared autowired service.
     *
     * @return \Eccube\Command\PluginGenerateCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Eccube'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'PluginGenerateCommand.php';

        $container->privates['Eccube\\Command\\PluginGenerateCommand'] = $instance = new \Eccube\Command\PluginGenerateCommand(($container->services['Eccube\\Common\\EccubeConfig'] ?? self::getEccubeConfigService($container)));

        $instance->setName('eccube:plugin:generate');

        return $instance;
    }
}
