<?php

namespace ContainerOzgN5sx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDeliveryCompanyRepositoryService extends Eccube_KernelDevDebugContainer
{
    /**
     * Gets the private 'Plugin\EccubePaymentLite42\Repository\DeliveryCompanyRepository' shared autowired service.
     *
     * @return \Plugin\EccubePaymentLite42\Repository\DeliveryCompanyRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'app'.\DIRECTORY_SEPARATOR.'Plugin'.\DIRECTORY_SEPARATOR.'EccubePaymentLite42'.\DIRECTORY_SEPARATOR.'Repository'.\DIRECTORY_SEPARATOR.'DeliveryCompanyRepository.php';

        return $container->privates['Plugin\\EccubePaymentLite42\\Repository\\DeliveryCompanyRepository'] = new \Plugin\EccubePaymentLite42\Repository\DeliveryCompanyRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
