<?php

namespace ContainerOzgN5sx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLoginHistoryListenerService extends Eccube_KernelDevDebugContainer
{
    /**
     * Gets the private 'Eccube\EventListener\LoginHistoryListener' shared autowired service.
     *
     * @return \Eccube\EventListener\LoginHistoryListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Eccube'.\DIRECTORY_SEPARATOR.'EventListener'.\DIRECTORY_SEPARATOR.'LoginHistoryListener.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['Eccube\\EventListener\\LoginHistoryListener'])) {
            return $container->privates['Eccube\\EventListener\\LoginHistoryListener'];
        }

        return $container->privates['Eccube\\EventListener\\LoginHistoryListener'] = new \Eccube\EventListener\LoginHistoryListener($a, ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->privates['Eccube\\Request\\Context'] ?? self::getContextService($container)), ($container->privates['Eccube\\Repository\\MemberRepository'] ?? $container->load('getMemberRepositoryService')), ($container->privates['Eccube\\Repository\\Master\\LoginHistoryStatusRepository'] ?? $container->load('getLoginHistoryStatusRepositoryService')));
    }
}
