<?php

namespace Container4Cunbzj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCustomerRepositoryDecoratorService extends Eccube_KernelDevDebugContainer
{
    /**
     * Gets the private 'Plugin\B2BConnector\Repository\CustomerRepositoryDecorator' shared autowired service.
     *
     * @return \Plugin\B2BConnector\Repository\CustomerRepositoryDecorator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Eccube'.\DIRECTORY_SEPARATOR.'Repository'.\DIRECTORY_SEPARATOR.'CustomerRepository.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'app'.\DIRECTORY_SEPARATOR.'Plugin'.\DIRECTORY_SEPARATOR.'B2BConnector'.\DIRECTORY_SEPARATOR.'Repository'.\DIRECTORY_SEPARATOR.'CustomerRepositoryDecorator.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['Plugin\\B2BConnector\\Repository\\CustomerRepositoryDecorator'])) {
            return $container->privates['Plugin\\B2BConnector\\Repository\\CustomerRepositoryDecorator'];
        }
        $b = ($container->services['doctrine'] ?? self::getDoctrineService($container));
        $c = ($container->privates['Eccube\\Doctrine\\Query\\Queries'] ??= new \Eccube\Doctrine\Query\Queries());
        $d = ($container->privates['Eccube\\Repository\\OrderRepository'] ?? self::getOrderRepositoryService($container));
        $e = ($container->services['Eccube\\Common\\EccubeConfig'] ?? self::getEccubeConfigService($container));

        return $container->privates['Plugin\\B2BConnector\\Repository\\CustomerRepositoryDecorator'] = new \Plugin\B2BConnector\Repository\CustomerRepositoryDecorator(new \Eccube\Repository\CustomerRepository($b, $c, $a, $d, $e), $b, $c, $a, $d, $e);
    }
}
