<?php

namespace Container4Cunbzj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrderPdfServiceService extends Eccube_KernelDevDebugContainer
{
    /**
     * Gets the private 'Eccube\Service\OrderPdfService' shared autowired service.
     *
     * @return \Eccube\Service\OrderPdfService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'tecnickcom'.\DIRECTORY_SEPARATOR.'tcpdf'.\DIRECTORY_SEPARATOR.'tcpdf.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'setasign'.\DIRECTORY_SEPARATOR.'fpdi'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'FpdiTrait.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'setasign'.\DIRECTORY_SEPARATOR.'fpdi'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Tcpdf'.\DIRECTORY_SEPARATOR.'Fpdi.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Eccube'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'OrderPdfService.php';

        $a = ($container->services['Eccube\\Service\\TaxRuleService'] ?? $container->load('getTaxRuleServiceService'));

        if (isset($container->privates['Eccube\\Service\\OrderPdfService'])) {
            return $container->privates['Eccube\\Service\\OrderPdfService'];
        }
        $b = ($container->privates['Eccube\\Twig\\Extension\\TaxExtension'] ?? self::getTaxExtensionService($container));

        if (isset($container->privates['Eccube\\Service\\OrderPdfService'])) {
            return $container->privates['Eccube\\Service\\OrderPdfService'];
        }

        return $container->privates['Eccube\\Service\\OrderPdfService'] = new \Eccube\Service\OrderPdfService(($container->services['Eccube\\Common\\EccubeConfig'] ?? self::getEccubeConfigService($container)), ($container->privates['Eccube\\Repository\\OrderRepository'] ?? self::getOrderRepositoryService($container)), ($container->privates['Eccube\\Repository\\ShippingRepository'] ?? $container->load('getShippingRepositoryService')), $a, ($container->privates['Eccube\\Repository\\BaseInfoRepository'] ?? self::getBaseInfoRepositoryService($container)), ($container->privates['Eccube\\Twig\\Extension\\EccubeExtension'] ?? self::getEccubeExtensionService($container)), $b);
    }
}
