<?php

namespace ContainerUoSsGvx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminProductSubscriberService extends Eccube_KernelDevDebugContainer
{
    /**
     * Gets the public 'Plugin\B2BConnector\Event\AdminProductSubscriber' shared autowired service.
     *
     * @return \Plugin\B2BConnector\Event\AdminProductSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'app'.\DIRECTORY_SEPARATOR.'Plugin'.\DIRECTORY_SEPARATOR.'B2BConnector'.\DIRECTORY_SEPARATOR.'Event'.\DIRECTORY_SEPARATOR.'AdminProductSubscriber.php';

        $a = ($container->privates['twig'] ?? self::getTwigService($container));

        if (isset($container->services['Plugin\\B2BConnector\\Event\\AdminProductSubscriber'])) {
            return $container->services['Plugin\\B2BConnector\\Event\\AdminProductSubscriber'];
        }
        $b = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->services['Plugin\\B2BConnector\\Event\\AdminProductSubscriber'])) {
            return $container->services['Plugin\\B2BConnector\\Event\\AdminProductSubscriber'];
        }
        $c = ($container->privates['form.factory'] ?? $container->load('getForm_FactoryService'));

        if (isset($container->services['Plugin\\B2BConnector\\Event\\AdminProductSubscriber'])) {
            return $container->services['Plugin\\B2BConnector\\Event\\AdminProductSubscriber'];
        }

        return $container->services['Plugin\\B2BConnector\\Event\\AdminProductSubscriber'] = new \Plugin\B2BConnector\Event\AdminProductSubscriber($a, $b, $c, ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)));
    }
}
