<?php

namespace ContainerUoSsGvx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrderHelperService extends Eccube_KernelDevDebugContainer
{
    /**
     * Gets the private 'Eccube\Service\OrderHelper' shared autowired service.
     *
     * @return \Eccube\Service\OrderHelper
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Eccube'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'OrderHelper.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['Eccube\\Service\\OrderHelper'])) {
            return $container->privates['Eccube\\Service\\OrderHelper'];
        }
        $b = ($container->privates['security.authorization_checker'] ?? self::getSecurity_AuthorizationCheckerService($container));

        if (isset($container->privates['Eccube\\Service\\OrderHelper'])) {
            return $container->privates['Eccube\\Service\\OrderHelper'];
        }

        return $container->privates['Eccube\\Service\\OrderHelper'] = new \Eccube\Service\OrderHelper($a, ($container->privates['Eccube\\Repository\\OrderRepository'] ?? self::getOrderRepositoryService($container)), ($container->privates['Eccube\\Repository\\Master\\OrderItemTypeRepository'] ?? $container->load('getOrderItemTypeRepositoryService')), ($container->privates['Eccube\\Repository\\Master\\OrderStatusRepository'] ?? $container->load('getOrderStatusRepositoryService')), ($container->privates['Eccube\\Repository\\DeliveryRepository'] ?? $container->load('getDeliveryRepositoryService')), ($container->privates['Eccube\\Repository\\PaymentRepository'] ?? $container->load('getPaymentRepositoryService')), ($container->privates['Eccube\\Repository\\Master\\DeviceTypeRepository'] ?? self::getDeviceTypeRepositoryService($container)), ($container->privates['Eccube\\Repository\\Master\\PrefRepository'] ?? $container->load('getPrefRepositoryService')), ($container->services['Detection\\MobileDetect'] ??= new \Detection\MobileDetect()), ($container->privates['Eccube\\Session\\Session'] ?? self::getSessionService($container)), $b, ($container->privates['security.token_storage'] ?? self::getSecurity_TokenStorageService($container)));
    }
}
