<?php

namespace ContainerMHKieht;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductReviewStatusRepositoryService extends Eccube_KernelDevDebugContainer
{
    /**
     * Gets the private 'Plugin\ProductReview42\Repository\ProductReviewStatusRepository' shared autowired service.
     *
     * @return \Plugin\ProductReview42\Repository\ProductReviewStatusRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'app'.\DIRECTORY_SEPARATOR.'Plugin'.\DIRECTORY_SEPARATOR.'ProductReview42'.\DIRECTORY_SEPARATOR.'Repository'.\DIRECTORY_SEPARATOR.'ProductReviewStatusRepository.php';

        return $container->privates['Plugin\\ProductReview42\\Repository\\ProductReviewStatusRepository'] = new \Plugin\ProductReview42\Repository\ProductReviewStatusRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
