<?php

namespace ContainerMHKieht;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRelatedProductRepositoryService extends Eccube_KernelDevDebugContainer
{
    /**
     * Gets the private 'Plugin\RelatedProduct42\Repository\RelatedProductRepository' shared autowired service.
     *
     * @return \Plugin\RelatedProduct42\Repository\RelatedProductRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'app'.\DIRECTORY_SEPARATOR.'Plugin'.\DIRECTORY_SEPARATOR.'RelatedProduct42'.\DIRECTORY_SEPARATOR.'Repository'.\DIRECTORY_SEPARATOR.'RelatedProductRepository.php';

        return $container->privates['Plugin\\RelatedProduct42\\Repository\\RelatedProductRepository'] = new \Plugin\RelatedProduct42\Repository\RelatedProductRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
