<?php

namespace ContainerMHKieht;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSearchProductRepositoryService extends Eccube_KernelDevDebugContainer
{
    /**
     * Gets the private 'Plugin\EccubePaymentLite42\Repository\SearchProductRepository' shared autowired service.
     *
     * @return \Plugin\EccubePaymentLite42\Repository\SearchProductRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'app'.\DIRECTORY_SEPARATOR.'Plugin'.\DIRECTORY_SEPARATOR.'EccubePaymentLite42'.\DIRECTORY_SEPARATOR.'Repository'.\DIRECTORY_SEPARATOR.'SearchProductRepository.php';

        return $container->privates['Plugin\\EccubePaymentLite42\\Repository\\SearchProductRepository'] = new \Plugin\EccubePaymentLite42\Repository\SearchProductRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)), ($container->privates['Eccube\\Doctrine\\Query\\Queries'] ??= new \Eccube\Doctrine\Query\Queries()), ($container->services['Eccube\\Common\\EccubeConfig'] ?? self::getEccubeConfigService($container)));
    }
}
