<?php

namespace ContainerBbFG9cz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminCustomerAddressSubscriberService extends Eccube_KernelProdDebugContainer
{
    /**
     * Gets the public 'Plugin\B2BConnector\Event\AdminCustomerAddressSubscriber' shared autowired service.
     *
     * @return \Plugin\B2BConnector\Event\AdminCustomerAddressSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'app'.\DIRECTORY_SEPARATOR.'Plugin'.\DIRECTORY_SEPARATOR.'B2BConnector'.\DIRECTORY_SEPARATOR.'Event'.\DIRECTORY_SEPARATOR.'AdminCustomerAddressSubscriber.php';

        return $container->services['Plugin\\B2BConnector\\Event\\AdminCustomerAddressSubscriber'] = new \Plugin\B2BConnector\Event\AdminCustomerAddressSubscriber(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)));
    }
}
