<?php

namespace ContainerBbFG9cz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCsvExportServiceService extends Eccube_KernelProdDebugContainer
{
    /**
     * Gets the private 'Eccube\Service\CsvExportService' shared autowired service.
     *
     * @return \Eccube\Service\CsvExportService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Eccube'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'CsvExportService.php';

        return $container->privates['Eccube\\Service\\CsvExportService'] = new \Eccube\Service\CsvExportService(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['Eccube\\Repository\\CsvRepository'] ?? $container->load('getCsvRepositoryService')), ($container->privates['Eccube\\Repository\\Master\\CsvTypeRepository'] ?? $container->load('getCsvTypeRepositoryService')), ($container->privates['Eccube\\Repository\\OrderRepository'] ?? self::getOrderRepositoryService($container)), ($container->privates['Eccube\\Repository\\ShippingRepository'] ?? $container->load('getShippingRepositoryService')), ($container->privates['Plugin\\B2BConnector\\Repository\\CustomerRepositoryDecorator'] ?? $container->load('getCustomerRepositoryDecoratorService')), ($container->privates['Eccube\\Repository\\ProductRepository'] ?? self::getProductRepositoryService($container)), ($container->services['Eccube\\Common\\EccubeConfig'] ?? self::getEccubeConfigService($container)), ($container->privates['form.factory'] ?? $container->load('getForm_FactoryService')), ($container->services['knp_paginator'] ?? $container->load('getKnpPaginatorService')));
    }
}
