<?php

namespace ContainerBbFG9cz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExceptionListenerService extends Eccube_KernelProdDebugContainer
{
    /**
     * Gets the private 'Eccube\EventListener\ExceptionListener' shared autowired service.
     *
     * @return \Eccube\EventListener\ExceptionListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Eccube'.\DIRECTORY_SEPARATOR.'EventListener'.\DIRECTORY_SEPARATOR.'ExceptionListener.php';

        $a = ($container->privates['twig'] ?? self::getTwigService($container));

        if (isset($container->privates['Eccube\\EventListener\\ExceptionListener'])) {
            return $container->privates['Eccube\\EventListener\\ExceptionListener'];
        }

        return $container->privates['Eccube\\EventListener\\ExceptionListener'] = new \Eccube\EventListener\ExceptionListener($a, ($container->privates['Eccube\\Request\\Context'] ?? self::getContextService($container)));
    }
}
