<?php

namespace ContainerBbFG9cz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInstallerCommandService extends Eccube_KernelProdDebugContainer
{
    /**
     * Gets the private 'Eccube\Command\InstallerCommand' shared autowired service.
     *
     * @return \Eccube\Command\InstallerCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Eccube'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'InstallerCommand.php';

        $container->privates['Eccube\\Command\\InstallerCommand'] = $instance = new \Eccube\Command\InstallerCommand(($container->services['Eccube\\Common\\EccubeConfig'] ?? self::getEccubeConfigService($container)));

        $instance->setName('eccube:install');

        return $instance;
    }
}
