<?php

namespace ContainerBbFG9cz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMonolog_Handler_GmoEpsilonService extends Eccube_KernelProdDebugContainer
{
    /**
     * Gets the private 'monolog.handler.gmo_epsilon' shared service.
     *
     * @return \Monolog\Handler\FingersCrossedHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = new \Monolog\Handler\RotatingFileHandler((\dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'log/prod/gmo_epsilon.log'), '60', 'debug', true, NULL, false);
        $a->pushProcessor(($container->privates['monolog.processor.psr_log_message'] ??= new \Monolog\Processor\PsrLogMessageProcessor()));
        $a->setFilenameFormat('{filename}-{date}', 'Y-m-d');
        $a->setFormatter(($container->privates['eccube.log.formatter.line'] ?? self::getEccube_Log_Formatter_LineService($container)));

        return $container->privates['monolog.handler.gmo_epsilon'] = new \Monolog\Handler\FingersCrossedHandler($a, new \Monolog\Handler\FingersCrossed\ErrorLevelActivationStrategy('error'), 0, true, true, 'info');
    }
}
