<?php

namespace ContainerBbFG9cz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRegularStatusRepositoryService extends Eccube_KernelProdDebugContainer
{
    /**
     * Gets the private 'Plugin\EccubePaymentLite42\Repository\RegularStatusRepository' shared autowired service.
     *
     * @return \Plugin\EccubePaymentLite42\Repository\RegularStatusRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'app'.\DIRECTORY_SEPARATOR.'Plugin'.\DIRECTORY_SEPARATOR.'EccubePaymentLite42'.\DIRECTORY_SEPARATOR.'Repository'.\DIRECTORY_SEPARATOR.'RegularStatusRepository.php';

        return $container->privates['Plugin\\EccubePaymentLite42\\Repository\\RegularStatusRepository'] = new \Plugin\EccubePaymentLite42\Repository\RegularStatusRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
