<?php

namespace ContainerBbFG9cz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurityListenerService extends Eccube_KernelProdDebugContainer
{
    /**
     * Gets the private 'Eccube\EventListener\SecurityListener' shared autowired service.
     *
     * @return \Eccube\EventListener\SecurityListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Eccube'.\DIRECTORY_SEPARATOR.'EventListener'.\DIRECTORY_SEPARATOR.'SecurityListener.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['Eccube\\EventListener\\SecurityListener'])) {
            return $container->privates['Eccube\\EventListener\\SecurityListener'];
        }
        $b = ($container->privates['Eccube\\Service\\CartService'] ?? self::getCartServiceService($container));

        if (isset($container->privates['Eccube\\EventListener\\SecurityListener'])) {
            return $container->privates['Eccube\\EventListener\\SecurityListener'];
        }
        $c = ($container->privates['eccube.purchase.flow.cart'] ?? $container->load('getEccube_Purchase_Flow_CartService'));

        if (isset($container->privates['Eccube\\EventListener\\SecurityListener'])) {
            return $container->privates['Eccube\\EventListener\\SecurityListener'];
        }

        return $container->privates['Eccube\\EventListener\\SecurityListener'] = new \Eccube\EventListener\SecurityListener($a, $b, $c, ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()));
    }
}
