<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUoSsGvx\Eccube_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUoSsGvx/Eccube_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUoSsGvx.legacy');

    return;
}

if (!\class_exists(Eccube_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUoSsGvx\Eccube_KernelDevDebugContainer::class, Eccube_KernelDevDebugContainer::class, false);
}

return new \ContainerUoSsGvx\Eccube_KernelDevDebugContainer([
    'container.build_hash' => 'UoSsGvx',
    'container.build_id' => 'ad7c0cf0',
    'container.build_time' => 1762246450,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUoSsGvx');
