<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4Cunbzj\Eccube_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4Cunbzj/Eccube_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container4Cunbzj.legacy');

    return;
}

if (!\class_exists(Eccube_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container4Cunbzj\Eccube_KernelDevDebugContainer::class, Eccube_KernelDevDebugContainer::class, false);
}

return new \Container4Cunbzj\Eccube_KernelDevDebugContainer([
    'container.build_hash' => '4Cunbzj',
    'container.build_id' => 'f3939ec4',
    'container.build_time' => 1763097038,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container4Cunbzj');
